name: First-GHA-test
on:
   push:
     branches: 
       -main 
         workflow-dispatch
jobs:
    b16-first-job:
      runs-on: ubuntu-latest
      steps:
       - name: message
         run: echo "welcome to the GHA by batch-16 Champs"
     
